### ISSUE TITLE
Setup without building

### ISSUE THREAD

**Issue by keho98** [noam-io/lemma-javascript#1]
Would it be possible to include a built version of Lemma.js in the release, or instructions to use this library without building?

**Comment by evanShap** [comment]
Hey Kevin,

Is this for browser or node use?  My understanding is that the build step
only automates the import of all dependencies, so it's not actually needed
to run stuff.  I will verify and add an example that doesn't require the
build step.

**Comment by keho98** [comment]
Hi Evan,

This was for use in browser - the documentation implies that lemma.js needs to be built. My understanding is that skipping the build step is possible, but requires everything in src to be included. It may be a bit more developer friendly to attach one built file to the release which can be used alone, or even better, a cdn hosted version of a built file.

**Comment by dethtron5000** [comment]
@keho98 Hi Kevin - 

We released a new version today which contains a `/dist` folder with pre-built libraries.  (Also you can now install with `bower` and/or `npm`.)
